#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controller:
  resource: '../src/Controller'
  type: annotation
  prefix: /api

api_login_check:
    path: /api/login_check
